CREATE TABLE IF NOT EXISTS roles (
  slug VARCHAR(32) PRIMARY KEY,
  nome VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'terapeuta',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users(email);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource VARCHAR(80) NOT NULL,
  action VARCHAR(40) NOT NULL,
  descricao TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_permissions_resource_action
  ON permissions(resource, action);

CREATE TABLE IF NOT EXISTS role_permissions (
  role VARCHAR(32) NOT NULL,
  permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  CONSTRAINT pk_role_permissions PRIMARY KEY (role, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_role
  ON role_permissions(role);

CREATE INDEX IF NOT EXISTS idx_role_permissions_permission
  ON role_permissions(permission_id);
