CREATE TABLE IF NOT EXISTS access_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  user_email VARCHAR(160) NOT NULL,
  ip_origem VARCHAR(64),
  user_agent VARCHAR(512),
  browser VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_access_logs_created_at
  ON access_logs(created_at);

CREATE INDEX IF NOT EXISTS idx_access_logs_user_id
  ON access_logs(user_id);

