CREATE TABLE IF NOT EXISTS user_paciente_vinculos_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  target_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  previous_role VARCHAR(32),
  next_role VARCHAR(32) NOT NULL,
  removed_paciente_ids JSONB NOT NULL,
  reason VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_user_paciente_vinculos_audit_removed_ids_array
    CHECK (jsonb_typeof(removed_paciente_ids) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_user_paciente_vinc_audit_target
  ON user_paciente_vinculos_audit(target_user_id);

CREATE INDEX IF NOT EXISTS idx_user_paciente_vinc_audit_actor
  ON user_paciente_vinculos_audit(actor_user_id);

CREATE INDEX IF NOT EXISTS idx_user_paciente_vinc_audit_created_at
  ON user_paciente_vinculos_audit(created_at);
